[tool.poetry]
name = "labelu-backend"
version = "0.1.0"
description = ""
authors = ["pengjinhu <pengjinhu@pjlab.org.cn>"]
readme = "README.md"
packages = [{include = "labelu_backend"}]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = {extras = ["all"], version = "^0.85.1"}


[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
flake8 = "^5.0.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
